const GET_GAMES_REQUEST = "GET_GAME_REQUEST";
const GET_GAMES_SUCCESS = "GET_GAME_SUCCESS";
const GET_GAMES_FAILURE = "GET_GAME_FAILURE";

export const types = {
    GET_GAMES_REQUEST,
    GET_GAMES_SUCCESS,
    GET_GAMES_FAILURE
}