const GET_GAMES_REQUEST = "GET_GAME_REQUEST";
const GET_GAMES_SUCCESS = "GET_GAME_SUCCESS";
const GET_GAMES_FAILURE = "GET_GAME_FAILURE";
const POST_GAMES_REQUEST = "POST_GAME_REQUEST";
const POST_GAMES_SUCCESS = "POST_GAME_SUCCESS";
const POST_GAMES_FAILURE = "POST_GAME_FAILURE";
const DELETE_GAMES_REQUEST = "DELETE_GAME_REQUEST";
const DELETE_GAMES_SUCCESS = "DELETE_GAME_SUCCESS";
const DELETE_GAMES_FAILURE = "DELETE_GAME_FAILURE";
const EDIT_GAMES_REQUEST = "EDIT_GAMES_REQUEST";
const EDIT_GAMES_SUCCESS = "EDIT_GAMES_SUCCESS";
const EDIT_GAMES_FAILURE = "EDIT_GAMES_FAILURE";

const UPDATE_OFFERS_LIST = "UPDATE_OFFERS_LIST"

export const types = {
    GET_GAMES_REQUEST,
    GET_GAMES_SUCCESS,
    GET_GAMES_FAILURE,
    POST_GAMES_REQUEST,
    POST_GAMES_SUCCESS,
    POST_GAMES_FAILURE,
    UPDATE_OFFERS_LIST,
    DELETE_GAMES_REQUEST,
    DELETE_GAMES_SUCCESS,
    DELETE_GAMES_FAILURE,
    EDIT_GAMES_REQUEST,
    EDIT_GAMES_SUCCESS,
    EDIT_GAMES_FAILURE
}