const PRODUCTS_GET_REQUEST = 'PRODUCTS_GET_REQUEST';
const PRODUCTS_GET_SUCCESS = 'PRODUCTS_GET_SUCCESS';
const PRODUCTS_GET_FAILURE = 'PRODUCTS_GET_FAILURE';
const PRODUCTS_POST_REQUEST = 'PRODUCTS_POST_REQUEST';
const PRODUCTS_POST_SUCCESS = 'PRODUCTS_POST_SUCCESS';
const PRODUCTS_POST_FAILURE = 'PRODUCTS_POST_FAILURE';

export const types = {
    PRODUCTS_GET_REQUEST,
    PRODUCTS_GET_SUCCESS,
    PRODUCTS_GET_FAILURE,
    PRODUCTS_POST_REQUEST,
    PRODUCTS_POST_SUCCESS,
    PRODUCTS_POST_FAILURE
};