const PRODUCTS_GET_REQUEST = 'PRODUCTS_GET_REQUEST';
const PRODUCTS_GET_SUCCESS = 'PRODUCTS_GET_SUCCESS';
const PRODUCTS_GET_FAILURE = 'PRODUCTS_GET_FAILURE';
const PRODUCTS_POST_REQUEST = 'PRODUCTS_POST_REQUEST';
const PRODUCTS_POST_SUCCESS = 'PRODUCTS_POST_SUCCESS';
const PRODUCTS_POST_FAILURE = 'PRODUCTS_POST_FAILURE';
const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST';
const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
const PRODUCT_DELETE_FAILURE = 'PRODUCT_DELETE_FAILURE';

const CATEGORIES_GET_REQUEST = 'CATEGORIES_GET_REQUEST';
const CATEGORIES_GET_SUCCESS = 'CATEGORIES_GET_SUCCESS';
const CATEGORIES_GET_FAILURE = 'CATEGORIES_GET_FAILURE';

const CATEGORY_PRODUCT_GET_REQUEST = 'CATEGORY_PRODUCT_GET_REQUEST';
const CATEGORY_PRODUCT_GET_SUCCESS = 'CATEGORY_PRODUCT_GET_SUCCESS';
const CATEGORY_PRODUCT_GET_FAILURE = 'CATEGORY_PRODUCT_GET_FAILURE';

export const types = {
    PRODUCTS_GET_REQUEST,
    PRODUCTS_GET_SUCCESS,
    PRODUCTS_GET_FAILURE,
    PRODUCTS_POST_REQUEST,
    PRODUCTS_POST_SUCCESS,
    PRODUCTS_POST_FAILURE,
    PRODUCT_DELETE_REQUEST,
    PRODUCT_DELETE_SUCCESS,
    PRODUCT_DELETE_FAILURE,
    CATEGORIES_GET_REQUEST,
    CATEGORIES_GET_SUCCESS,
    CATEGORIES_GET_FAILURE,
    CATEGORY_PRODUCT_GET_REQUEST,
    CATEGORY_PRODUCT_GET_SUCCESS,
    CATEGORY_PRODUCT_GET_FAILURE
};