const GET_PRODUCERS_REQUEST = 'GET_PRODUCERS_REQUEST';
const GET_PRODUCERS_SUCCESS = 'GET_PRODUCERS_SUCCESS';
const GET_PRODUCERS_FAILURE = 'GET_PRODUCERS_FAILURE';
const POST_PRODUCERS_REQUEST = 'POST_PRODUCERS_REQUEST';
const POST_PRODUCERS_SUCCESS = 'POST_PRODUCERS_SUCCESS';
const POST_PRODUCERS_FAILURE = 'POST_PRODUCERS_FAILURE';

export const types = {
    GET_PRODUCERS_REQUEST,
    GET_PRODUCERS_SUCCESS,
    GET_PRODUCERS_FAILURE,
    POST_PRODUCERS_REQUEST,
    POST_PRODUCERS_SUCCESS,
    POST_PRODUCERS_FAILURE
}