const GET_PRODUCERS_REQUEST = 'GET_PRODUCERS_REQUEST';
const GET_PRODUCERS_SUCCESS = 'GET_PRODUCERS_SUCCESS';
const GET_PRODUCERS_FAILURE = 'GET_PRODUCERS_FAILURE';

export const types = {
    GET_PRODUCERS_REQUEST,
    GET_PRODUCERS_SUCCESS,
    GET_PRODUCERS_FAILURE
}