const GET_CURRENCIES_REQUEST = 'GET_CURRENCIES_REQUEST';
const GET_CURRENCIES_SUCCESS = 'GET_CURRENCIES_SUCCESS';
const GET_CURRENCIES_FAILURE = 'GET_CURRENCIES_FAILURE';

export const types = {
    GET_CURRENCIES_REQUEST,
    GET_CURRENCIES_SUCCESS,
    GET_CURRENCIES_FAILURE
}