const CARTS_GET_REQUEST = 'CARTS_GET_REQUEST';
const CARTS_GET_SUCCESS = 'CARTS_GET_SUCCESS';
const CARTS_GET_FAILURE = 'CARTS_GET_FAILURE';
const ONE_CART_GET_REQUEST = 'ONE_CART_GET_REQUEST';
const ONE_CART_GET_SUCCESS = 'ONE_CART_GET_SUCCESS';
const ONE_CART_GET_FAILURE = 'ONE_CART_GET_FAILURE';

const ADD_TO_CART = 'ADD_TO_CART';

const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST';
const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
const ADD_TO_CART_FAILURE = 'ADD_TO_CART_FAILURE';
const NEW_CART_REQUEST = 'NEW_CART_REQUEST';
const NEW_CART_SUCCESS = 'NEW_CART_SUCCESS';
const NEW_CART_FAILURE = 'NEW_CART_FAILURE';
const DELETE_CART_REQUEST = 'DELETE_CART_REQUEST';
const DELETE_CART_SUCCESS = 'DELETE_CART_SUCCESS';
const DELETE_CART_FAILURE = 'DELETE_CART_FAILURE';

export const types = {
    CARTS_GET_REQUEST,
    CARTS_GET_SUCCESS,
    CARTS_GET_FAILURE,
    ONE_CART_GET_REQUEST,
    ONE_CART_GET_SUCCESS,
    ONE_CART_GET_FAILURE,
    ADD_TO_CART,
    ADD_TO_CART_REQUEST,
    ADD_TO_CART_SUCCESS,
    ADD_TO_CART_FAILURE,
    NEW_CART_REQUEST,
    NEW_CART_SUCCESS,
    NEW_CART_FAILURE,
    DELETE_CART_REQUEST,
    DELETE_CART_SUCCESS,
    DELETE_CART_FAILURE
}