const CARTS_GET_REQUEST = 'CARTS_GET_REQUEST';
const CARTS_GET_SUCCESS = 'CARTS_GET_SUCCESS';
const CARTS_GET_FAILURE = 'CARTS_GET_FAILURE';
const ONE_CART_GET_REQUEST = 'ONE_CART_GET_REQUEST';
const ONE_CART_GET_SUCCESS = 'ONE_CART_GET_SUCCESS';
const ONE_CART_GET_FAILURE = 'ONE_CART_GET_FAILURE';

export const types = {
    CARTS_GET_REQUEST,
    CARTS_GET_SUCCESS,
    CARTS_GET_FAILURE,
    ONE_CART_GET_REQUEST,
    ONE_CART_GET_SUCCESS,
    ONE_CART_GET_FAILURE
}