const GET_OFFERS_REQUEST = "GET_OFFERS_REQUEST";
const GET_OFFERS_SUCCESS = "GET_OFFERS_SUCCESS";
const GET_OFFERS_FAILURE = "GET_OFFERS_FAILURE";
const POST_OFFERS_REQUEST = "POST_OFFERS_REQUEST";
const POST_OFFERS_SUCCESS = "POST_OFFERS_SUCCESS";
const POST_OFFERS_FAILURE = "POST_OFFERS_FAILURE";

export const types = {
    GET_OFFERS_REQUEST,
    GET_OFFERS_SUCCESS,
    GET_OFFERS_FAILURE,
    POST_OFFERS_REQUEST,
    POST_OFFERS_SUCCESS,
    POST_OFFERS_FAILURE
}