const GET_OFFERS_REQUEST = "GET_OFFERS_REQUEST";
const GET_OFFERS_SUCCESS = "GET_OFFERS_SUCCESS";
const GET_OFFERS_FAILURE = "GET_OFFERS_FAILURE";

export const types = {
    GET_OFFERS_REQUEST,
    GET_OFFERS_SUCCESS,
    GET_OFFERS_FAILURE
}