const USER_GET_REQUEST = 'USER_GET_REQUEST';
const USER_GET_SUCCESS = 'USER_GET_SUCCESS';
const USER_GET_FAILURE = 'USER_GET_FAILURE';
const ONE_USER_GET_REQUEST = 'ONE_USER_GET_REQUEST';
const ONE_USER_GET_SUCCESS = 'ONE_USER_GET_SUCCESS';
const ONE_USER_GET_FAILURE = 'ONE_USER_GET_FAILURE';

export const types = {
    USER_GET_REQUEST,
    USER_GET_SUCCESS,
    USER_GET_FAILURE,
    ONE_USER_GET_REQUEST,
    ONE_USER_GET_SUCCESS,
    ONE_USER_GET_FAILURE
};