const USER_GET_REQUEST = 'USER_GET_REQUEST';
const USER_GET_SUCCESS = 'USER_GET_SUCCESS';
const USER_GET_FAILURE = 'USER_GET_FAILURE';

export const types = {
    USER_GET_REQUEST,
    USER_GET_SUCCESS,
    USER_GET_FAILURE,
};